### ISSUE TITLE
Couldn't push the artifact to s3 bucket on mvn deploy

### ISSUE THREAD

**Issue by prayagupa** [wbingli/maven-s3-repo#1]
Hi @wbinglee , 
1) I wanted to imitate what you did to `s3` to push the artifact of project [usergrid](https://github.com/PseudononymousEpistle/incubator-usergrid/blob/master/stack/pom.xml), 
I configured `~/.m2/settings.xml` and `pom`  for the project whose artifact needs to be pushed is

``` xml
   166   <distributionManagement>                                                                                                                     
~  167     <!-- aws s3 release repo -->                                                                    
   168     <repository>                                                                                    
~  169         <id>aws-release</id>                                                                        
~  170         <name>AWS S3 Release Repository</name>                                                      
~  171         <url>s3://maven.prayagupd.co/release</url>                                                 
_  172     </repository>                                                                                   
   173     <snapshotRepository>                                                                            
~  174         <id>aws-snapshot</id>                                                                       
~  175         <name>AWS S3 Snapshot Repository</name>                                                     
~  176         <url>s3://maven.prayagupd.co/snapshot</url>                                                
   177     </snapshotRepository>                                                                           
+  178     <!-- aws s3 release repo -->                                                                    
+  179                                                                                                     
   180   </distributionManagement>   


+ 1373    <!-- build extensions-->                                                                         
+ 1374     <extensions>                                                                                                                               
+ 1375       <extension>                                                                                   
+ 1376         <groupId>org.springframework.build</groupId>                                                
+ 1377         <artifactId>aws-maven</artifactId>                                                          
+ 1378         <version>5.0.0.RELEASE</version>                                                            
+ 1379       </extension>                                                                                  
+ 1380     </extensions>                                                                                   
+ 1381    <!-- build extensions-->   
```

2) When I want to push the artifact to s3 bucket with `mvn deploy -X`, I get following error

``` bash
[INFO] Total time: 1:10.959s
[INFO] Finished at: Thu Oct 23 19:14:41 NPT 2014
[INFO] Final Memory: 31M/262M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.6:deploy (default-deploy) on project usergrid: Failed to deploy artifacts: Could not transfer artifact org.apache.usergrid:usergrid:pom:1.0.0 from/to aws-release (s3://maven.prayagupd.co/release): Unable to unmarshall response (Couldn't initialize a SAX driver to create an XMLReader). Response Code: 200, Response Text: OK: SAX2 driver class org.apache.xerces.parsers.SAXParser not found -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.6:deploy (default-deploy) on project usergrid: Failed to deploy artifacts: Could not transfer artifact org.apache.usergrid:usergrid:pom:1.0.0 from/to aws-release (s3://maven.prayagupd.co/release): Unable to unmarshall response (Couldn't initialize a SAX driver to create an XMLReader). Response Code: 200, Response Text: OK
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to deploy artifacts: Could not transfer artifact org.apache.usergrid:usergrid:pom:1.0.0 from/to aws-release (s3://maven.prayagupd.co/release): Unable to unmarshall response (Couldn't initialize a SAX driver to create an XMLReader). Response Code: 200, Response Text: OK
    at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:192)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
Caused by: org.apache.maven.artifact.deployer.ArtifactDeploymentException: Failed to deploy artifacts: Could not transfer artifact org.apache.usergrid:usergrid:pom:1.0.0 from/to aws-release (s3://maven.prayagupd.co/release): Unable to unmarshall response (Couldn't initialize a SAX driver to create an XMLReader). Response Code: 200, Response Text: OK
    at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:141)
    at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:148)
    ... 21 more
Caused by: org.sonatype.aether.deployment.DeploymentException: Failed to deploy artifacts: Could not transfer artifact org.apache.usergrid:usergrid:pom:1.0.0 from/to aws-release (s3://maven.prayagupd.co/release): Unable to unmarshall response (Couldn't initialize a SAX driver to create an XMLReader). Response Code: 200, Response Text: OK
    at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:280)
    at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:211)
    at org.sonatype.aether.impl.internal.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:443)
    at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:137)
    ... 22 more
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache.usergrid:usergrid:pom:1.0.0 from/to aws-release (s3://maven.prayagupd.co/release): Unable to unmarshall response (Couldn't initialize a SAX driver to create an XMLReader). Response Code: 200, Response Text: OK
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:941)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:837)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.put(WagonRepositoryConnector.java:467)
    at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:274)
    ... 25 more
Caused by: com.amazonaws.AmazonClientException: Unable to unmarshall response (Couldn't initialize a SAX driver to create an XMLReader). Response Code: 200, Response Text: OK
    at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:713)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:395)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3384)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3336)
    at com.amazonaws.services.s3.AmazonS3Client.getBucketLocation(AmazonS3Client.java:669)
    at com.amazonaws.services.s3.AmazonS3Client.getBucketLocation(AmazonS3Client.java:677)
    at org.springframework.build.aws.maven.SimpleStorageServiceWagon.connectToRepository(SimpleStorageServiceWagon.java:86)
    at org.springframework.build.aws.maven.AbstractWagon.connect(AbstractWagon.java:146)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.connectWagon(WagonRepositoryConnector.java:345)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.pollWagon(WagonRepositoryConnector.java:385)
    at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:803)
    ... 27 more
Caused by: com.amazonaws.AmazonClientException: Couldn't initialize a SAX driver to create an XMLReader
    at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:112)
    at com.amazonaws.services.s3.model.transform.Unmarshallers$BucketLocationUnmarshaller.unmarshall(Unmarshallers.java:119)
    at com.amazonaws.services.s3.model.transform.Unmarshallers$BucketLocationUnmarshaller.unmarshall(Unmarshallers.java:116)
    at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62)
    at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:31)
    at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:687)
    ... 38 more
Caused by: org.xml.sax.SAXException: SAX2 driver class org.apache.xerces.parsers.SAXParser not found
java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
    at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:229)
    at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:190)
    at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:110)
    ... 43 more
Caused by: java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
    at org.xml.sax.helpers.NewInstance.newInstance(NewInstance.java:73)
    at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:227)
    ... 45 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by manzke** [comment]
I don't know the actual cause of it, but I have found at least a workaround.

mvn deploy -Dorg.xml.sax.driver="com.sun.org.apache.xerces.internal.parsers.SAXParser"

**Comment by wbingli** [comment]
I will close this issue as it's 3 years old. Open a new issue and I will response, Sorry.
